"""Initial migration with all models

Revision ID: 39a142a85b63
Revises: 
Create Date: 2026-01-15 19:53:35.327071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '39a142a85b63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_highlights_id', table_name='project_highlights')
    op.drop_table('project_highlights')
    op.alter_column('food_logs', 'image_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_logs', 'image_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.create_table('project_highlights',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('tagline', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('tech_stack', sqlite.JSON(), nullable=True),
    sa.Column('future_goals', sqlite.JSON(), nullable=True),
    sa.Column('links', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_highlights_id', 'project_highlights', ['id'], unique=False)
    # ### end Alembic commands ###
